### ISSUE TITLE
Have you considered using JSON:api ?

### ISSUE THREAD

**Issue by mclarke** [civicrm/api4#1]
http://jsonapi.org/

**Comment by colemanw** [comment]
I like it!
... I think.
Let's ponder how our data model can fit into that structure, and whether we want the slight usability hit on the developer side of having to dig through 2 layers of json to get to the real data.

**Comment by mclarke** [comment]
I have no practical experience with it, sadly (only heard about it a week ago!) -- and it will certainly add a layer/learning-curve. But the anti-bikeshedding aspect seems really appealing. I've spent way too much time in the past arguing aesthetics of json payloads :) Also, as a frequent consumer of new apis, I've wished in the past for some sort of spec.

Could focus the project on key decisions that are project-specific rather than general.

I heard about it from this podcast: https://changelog.com/189/

**Comment by ErichBSchulz** [comment]
seems interesting https://www.google.com.au/trends/explore?q=jsonapi

**Comment by colemanw** [comment]
The trends are telling - all-in-all this is not a popular standard, nor is it getting wide adoption. Compare it to CiviCRM for example and jsonapi is much lower.
IMO if we are to adopt a 3rd-party standard it should be more popular than us, not less.

**Comment by ErichBSchulz** [comment]
using a standard pattern has some pluses tho... 

FYI the repo has 4280 stars and 197 watches and 183 contributors... https://github.com/json-api/json-api 

cf 175 stars and 50 watches and 234 contributors for https://github.com/civicrm/civicrm-core

so I don't think we should write it off just yet

**Comment by totten** [comment]
+1 closing the issue, -1 writing off the idea.

If someone is inclined to write a JSON-API binding, write that as a separate extension that builds around `civicrm_api()`. Use `Entity.get` and  `getfields` and `getactions` and so on. You can include support for APIv3 or APIv4 that way. (And if there's something missing from the metadata, then patch the ornery metadata.)

Longer version of the above from a previous off-list discussion:

> JFYI, I find this kind of request a little sideways. The API kernel was heavily influenced by my experience trying to create some kind of standards-compliant REST interface to the (unmerged) Doctrine project. 
>
> The main thing you need to implement something like json-api well is good metadata (same for HAL/HATEOAS, or RESTful interfaces generally, or SOAP interfaces, or JSON-RPC, or XML-RPC, or BreezeJS, or CLI, or Drupal Entity, or Pentaho/Talend GUI, ad nauseum) and authentication APIs.
>
> Many things are basically orthogonal to those problems: the PHP calling notation (e.g. “civicrm_api()” vs “Civi\Api4\Participant::create()”), the backend file layout ("api/v3/Participant.php" vs "Civi/Api4/Participant/Create.php”), the generic-vs-bespoke API implementations, etc. The main thing is to have one calling pattern and a clear way to get metadata.
>
> I think that “json-api binding” for civicrm_api() would be a good extension to incubate. (If someone wants to work on that, we should officially bless them and give them pointers/infra.) But it’s orthogonal to the problem that originally motivated the APIv4 discussion.
