### ISSUE TITLE
Support the same field in a query twice

### ISSUE THREAD

**Issue by colemanw** [civicrm/api4#10]
It would be fairly easy to tweak the syntax so that you can add the same field twice to a query. Use case:

      \Civi\Api4\Contact::get()
        ->addWhere('last_name', 'LIKE', 'smi%')
        ->addWhere('last_name', '!=', 'smith')
        ->execute();

**Comment by ErichBSchulz** [comment]
I think I can do this while sorting out #11 

here's to trying

**Comment by ErichBSchulz** [comment]
@colemanw I think we can close this one too :-)
