### ISSUE TITLE
Stability or MVP as a goal

### ISSUE THREAD

**Issue by ErichBSchulz** [civicrm/api4#13]
I have been discussing the API4 with @colemanw lately (thanks for all the pointers @colemanw!!)

There is one thing that is troubling me a bit though and this is the trade-off between getting progress with an early prototype [MVP](https://en.wikipedia.org/wiki/Minimum_viable_product) vs the notion of "getting it right".

I have heaps of sympathy for the idea of "keep it simple and just get it working"... *except* this is `Version 4` we are talking about.

It feels to me like `Version 3` *is* the `MVP` and we need to pause and address a few issues (notably around scalability and performance).

But I'm just trying to get a sense of how urgent the V4 MVP is. Is it urgent and I should focus effort on V5 (omg)... or do we have a bit of time to try and work up some more audacious goals for V4??

**Comment by ErichBSchulz** [comment]
(sorry if this is a bit abstract - I need to repackage some musings on [extra principles](https://docs.google.com/document/d/1N_kGR2LHLcLFk0eBAv7Ac-v9Ry3nADMue3sfnSaIZMg/edit?usp=sharing) and also so notes i left on the wiki)

**Comment by nganivet** [comment]
Highjacking this thread to reinforce that IMO the API should without a 
shred of doubt be business-focused (rather than a database-access 
layer). As such, it's entities should be business entities, not database 
tables, and I could not subscribe more to footnote #3 in the Google Doc 
on REST interface design.

Very concrete use case today: a large customer of mine has non D/WP/J! 
website, and a separate CiviCRM instance. He wants to implement event 
registration on his website - trivial to do via APIs since all the 
events are free. His question: if we use the API to create event 
registration in the CRM, is all the business logic applied? For example, 
if using the (Participant, create) call and the event is over capacity, 
is the person automatically put on the waiting list? Or will the API 
call result in the event being over-booked?

We've said for years that there is too much business logic in the forms 
layer and that this was a huge mistake. As we're moving to 
Angular/client-side interfaces for CiviCRM, we've also said that these 
interfaces should only use the API to remotely interact with CiviCRM. So 
the question is ... are we going to do the same mistake: code all 
business logic in Angular and use the API as a remote-database layer? Or 
are we going to do things right, have Angular call a business-level API 
and have all business logic done in core (BAO layer or equivalent)?

If business-oriented, it means we have to a) get rid of a number of 
'intermediary' entities that serve only as join tables or implementation 
details and b) add 'business' action verbs, that are entity-specific, on 
top of the CRUD actions.

</hijacking>

------ Original Message ------

**Comment by jackrabbithanna** [comment]
I think MVP and "getting it right" are the same thing, or more accurately V=right. Minimum Viable Product should be the "right"  foundational extensible architecture.  Perhaps it doesn't include every feature that we could think of, but if its extensible, many different people can add to it as their use cases require it.

I generally agree with nganivet, although there are times when you want to alter data in the tables without business logic after the fact. It seems like adding business action verbs is the way to go, and properly document these better actions, AND continue to have a solid architecture for addition of actions through extensions

**Comment by ErichBSchulz** [comment]
@nganivet I've move your hijack to its own issue now #14 so hopefully threads wont get too tangled

**Comment by ErichBSchulz** [comment]
In order to explain and clarify what I'm getting at here I've split a few issues that I think underpin my `stability`-vs-`rapid MPV` anxiety: #18 and #17 are the biggest ones having me reach for a paper bag

**Comment by ErichBSchulz** [comment]
Thanks @colemanw! that is a useful clarification - I love the sound of getting a full test suite early.

This leaves the issue of the importance of achieving stability as one of the high-level goals... for marking the "ready for release" requiring some high level of certainty that all the key requirements have been put in place and that the released API is able to be extended to accomodate them (even if the initial release doesn't include all features)

**Comment by JoeMurray** [comment]
In terms of high level scope, I think there are pain points in APIv3 and some nice promises for APIv4. I don't think we have modelled our BAO classes towards business oriented actions as much as would be desirable. The upside is that historically we were able to do a CRUD api fairly cheaply on BAO's that are mostly table oriented. The downside is that we haven't been thinking enough in business terms like register, join, send, attend, refund, etc., parsing them instead into CRUD operations first, that then assemble a business process of other CRUDs. @ErichBSchulz I think it is fine to be doing some blue-sky-ing, but there's also a fear of choosing a scope that won't be complete-able...like assuming we can quickly identify and refactor our BAOs to a new set of more business oriented methods that are more loosely coupled.

**Comment by nganivet** [comment]
+1: we haven't been thinking enough in business terms like register, join, send, attend, refund, etc.
If we are not tackling this in API v4 we will get back to having all business logic in the forms layer (now Angular instead of Quickform, but same principle). I don't think anyone wants that, so let's not make it easy by exposing the plumbing in the API: let's only expose the porcelain. This will force a sound architecture for moving CiviCRM forward.

**Comment by eileenmcnaughton** [comment]
Hmm - if we release an api that doesn't make it easy then we release an api that no-one will use. There is nothing stopping us from working on those other business api in v3 or v4 - let's not make it an obstacle

**Comment by JoeMurray** [comment]
@nganivet and @ErichSchultz I would prefer to see us adding new more business oriented entities first before deprecating or especially removing existing APIs. Iterate more.

**Comment by nganivet** [comment]
On the opposite, it will make the API so much easier if it is 'business-oriented': a single membership.renew call is just so much easier than calculating/assembling line items in a contribution, finding the proper financial types, creating the payment, checking that it went through, calculating the new membership start/end dates based on the previous membership type and current membership dates, starting a transaction to be able to backtrack if anything goes wrong, then pushing all these API calls one at a time and hoping nothing is gonna go wrong midway through (wait .. what if the user loses wireless connectivity just after we processed payment but before we had time to create the new membership .... ???).

Well, exaggerating a little bit but you certainly get my point ... business API are IMO cleaner and easier.

**Comment by nganivet** [comment]
@JoeMurray agreed. I like Tim's suggestion of starting with the Activity/ActivityContact functional scope and will probably tackle the specs there.

Would you be able to spec out what's needed to obsolete the 'civicrm_financial_trxn, civicrm_financial_item, civicrm_entity_financial_trxn, and perhaps even civicrm_contribution and civicrm_line_item', maybe based on the Order API or other business method on more general entities?

**Comment by eileenmcnaughton** [comment]
@nganivet I absolutely agree good methods will be  helpful when they are done. Just to repeat for people who are new to this conversation - the process for creating a new api method (in v3 or v4 api is)

1) log a JIRA with the suggestion
2) socialise it - email the dev list inviting feedback
3) adjust spec to incorporate feedback & announce that you are proceeding with the revised spec
4) write unit tests
5) write code
6) engage in review process to ensure your work gets reviewed & into core (you should expect the reviewer will need to spend 30%-200% as long reviewing as you have to write so please be sensible with your expectations here. The more work you put into the earlier stages the easier this will be to get done

**Comment by nganivet** [comment]
@eileen - can you please give us a chance to do that for a few functional domains before rushing to implement all the plumbing in API v4?

**Comment by eileenmcnaughton** [comment]
I don't think we have been rushing - the api project stalled on this issue a year ago! Hopefully it is restarting now - Erich has added a couple of coding entities.

**Comment by ErichBSchulz** [comment]
I was hoping to focus this issue on discussion about commitment to a stable API (which requires first sorting out a bunch of other stuff that have their own issues) 

@eileenmcnaughton @JoeMurray I think the issue with stability isn't to take on a bunch of work for ourselves - potentially quite the opposite - buy explicitly stating that API4 wont support a bunch of CRUD type operations *ever* because (1) these operations dont make sense as standalone operations (2) API3 has the important ones covered already and (3) core code can access the BAO/DAO layer.

I sense the biggest can of worms ( :dragon: ) for getting an API signature that everyone isn't going to hate in 4 years is #31 

But I keen to keep this open for a bit longer to attempt to collate some views... so far I have Eileen and Joe in the "for God's sake just do something" pile, while I seem to be in the "OMG I dont want to publish an API we will regret" (these might be slightly poetic labels of the piles)

on the basis that I'm currently out-voted I think the best thing I can do is hunker down and hope for company ;-)

**Comment by nganivet** [comment]
@ErichBSchulz @eileenmcnaughton These point of view are not antagonistic: we need to a) provide CRUD operations on business entities, and b) only implement business entities in API v4, and implement these well.

IMO API v3 provided a) reasonably well (ie. when creating a membership, related memberships were also created - a database CRUD would not have), but dramatically failed at b).

So if we started with defining what our 'trivial' business entities are (ie. Contact, Membership, Event, Grant, ...) and implement CRUD on these we've already made progress and satisfied both of your piles. We can then implement 'trivial' business methods on these entities (ie. tag & untag, merge, export, ...).

The next step is to go one level down, ie. are Phone and Email multi-valued attributes of the Contact entity or business entities on their own? What about an event registration? A group vs a smart group? A soft credit? Once decided, we can then either implement the business entity (most certainly include CRUD operations as a start), or tweak the business object's method to manage these additional attributes (ie. return => email will return only the primary email while return=> emails will return all emails).

Finally, we can now look at what slipped through the cracks (ie. System settings, Email templates, etc.) and implement the rest as needed.

Makes sense? Thoughts?

**Comment by eileenmcnaughton** [comment]
Perhaps it would be fairer to say we all agree on a and we have differing views on b than that api v3 failed at b. I disagree with quite a bit of your vision above but want to focus on points of agreement.

I agree that if we focus on getting our crud for contact, contribution, membership and participant and activity then we will have a useful apiv4 - even if the api only contains those entities and we continue to use apiv3 for everything else it provides a path for us to break the relationship between the api and the crufty-form-driven query object.

There are some specific api functions we can all agree about not bringing across - the survey respondant api, activity type api and constant api.

**Comment by nganivet** [comment]
@eileenmcnaughton Sorry if my language was a bit harsh on b), I was trying to make a point and this comment of course reflects my own opinion only (hence prefixing the sentence with IMO). I did not mean to offend you or anyone else, or diminish any of the hard work that has gone into creating & maintaining API v3 -- all of which I truly admire.

Also agreed on our points of agreement, so at least we have found a way to move forward and keep all satisfied in the short term!

**Comment by ErichBSchulz** [comment]
except I am concerned that allowing CRUD (even on core business entities) does not present a stable API

and basic CRUD is a good way to violate [dont expose implementation](https://github.com/civicrm/api4/issues/42) and [no occult side effects](https://github.com/civicrm/api4/issues/28)

**Comment by eileenmcnaughton** [comment]
The stability comes from the unit tests. 

One way to look at is is the api v4 should decrease the occult side effects (e.g the bizarreness of the contribution api). I think the concerns about exposing implementation relate to caching - which is something I believe could be added later

**Comment by xurizaemon** [comment]
There are three points in #42 re exposing details - won't copy them in here, yes one of them is caching.

**Comment by ErichBSchulz** [comment]
hey thanks folk

I think we can all agree we want a "stable MVP with tests" so perhaps best to close this and keep the other more pointy issues open.

yes for unit testing! :-) 

sorry I'm a bit slow on uptake sometime 

I don't think I've properly made the case yet on some of the other stuff - but me just being slow to get it is possible explanation.

I feel like I'm making progress on the "stable MVP with tests" currently so all this broader stuff I'd like to work through isn't holding me back

**Comment by colemanw** [comment]
+1 for moving forward with what we agree on so far :)
