### ISSUE TITLE
failing tests

### ISSUE THREAD

**Issue by ErichBSchulz** [civicrm/api4#2]
I'm not sure if this is expected or not:

```
root@209e1d6cabeb:/opt/buildkit/build/dmaster/sites/default/files/civicrm/ext/api4# phpunit4
PHPUnit 4.8.21 by Sebastian Bergmann and contributors.

Installing dmastertes_w0qpz schema
EE..

Time: 1.61 minutes, Memory: 33.50Mb

There were 2 errors:

1) Civi\API\V4\ParticipantTest::testGetActions
Civi\API\Exception\NotImplementedException: API (Participant, getActions) does not exist (join the API team and implement it!)

/opt/buildkit/build/dmaster/sites/all/modules/civicrm/Civi/API/Kernel.php:223
/opt/buildkit/build/dmaster/sites/all/modules/civicrm/Civi/API/Kernel.php:166
/opt/buildkit/build/dmaster/sites/default/files/civicrm/ext/api4/Civi/API/V4/Action.php:161
/opt/buildkit/build/dmaster/sites/default/files/civicrm/ext/api4/tests/phpunit/Civi/API/V4/ParticipantTest.php:18
/opt/buildkit/bin/phpunit4:545

2) Civi\API\V4\ParticipantTest::testGet
Civi\API\Exception\NotImplementedException: API (Participant, get) does not exist (join the API team and implement it!)

/opt/buildkit/build/dmaster/sites/all/modules/civicrm/Civi/API/Kernel.php:223
/opt/buildkit/build/dmaster/sites/all/modules/civicrm/Civi/API/Kernel.php:166
/opt/buildkit/build/dmaster/sites/default/files/civicrm/ext/api4/Civi/API/V4/Action.php:161
/opt/buildkit/build/dmaster/sites/default/files/civicrm/ext/api4/tests/phpunit/Civi/API/V4/ParticipantTest.php:38
/opt/buildkit/bin/phpunit4:545

FAILURES!
Tests: 4, Assertions: 5, Errors: 2.
```

**Comment by colemanw** [comment]
I just ran into the same thing and after some fruitless debugging realized the extension was not installed.
For some reason the command `cv en api4` does not work. :confused: 
However I was able to install the extension via the normal UI (yes, using a *mouse*) and everything worked after that.

**Comment by ErichBSchulz** [comment]
oh - is that a cv bug then?

**Comment by colemanw** [comment]
Haven't tracked it down. Not sure.

**Comment by ErichBSchulz** [comment]
for what its worth, after doing a refresh (with mouse) of extension and re-running tests I get:

```
root@209e1d6cabeb:/opt/buildkit/build/dmaster/sites/default/files/civicrm/ext/api4# phpunit4 -v
PHPUnit 4.8.21 by Sebastian Bergmann and contributors.

Runtime:	PHP 5.5.9-1ubuntu4.20
Configuration:	/opt/buildkit/build/dmaster/sites/default/files/civicrm/ext/api4/phpunit.xml.dist

.I..

Time: 683 ms, Memory: 27.50Mb

There was 1 incomplete test:

1) Civi\API\V4\ParticipantTest::testGet

/opt/buildkit/build/dmaster/sites/default/files/civicrm/ext/api4/tests/phpunit/Civi/API/V4/ParticipantTest.php:48
/opt/buildkit/bin/phpunit4:545

OK, but incomplete, skipped, or risky tests!
Tests: 4, Assertions: 10, Incomplete: 1.
root@209e1d6cabeb:/opt/buildkit/build/dmaster/sites/default/files/civicrm/ext/api4# 
```

**Comment by colemanw** [comment]
Good. That's what you should be getting.

**Comment by totten** [comment]
@colemanw  Regarding `cv` and `org.civicrm.api4`:
 * Maybe my memory is playing tricks or I'm looking the wrong place, but I thought there was a comment about  `cv dl --dev api4`. This makes sense to me -- the extension isn't published on https://civicrm.org/extensions . You need list the extension (along with an alpha or beta release).
 * For `cv en api4`, you might have an issue if it was a fresh download (because civicrm-core keeps a cached index of local extensions). `cv en -r api4` will refresh the cache. (I'm really tempted to make `-r` the default but looking for second opinions.)

**Comment by totten** [comment]
Note: Updated `cv dl` and `cv en` to auto-refresh the extension-cache if a name is unrecognized (e.g. https://github.com/civicrm/cv/commit/64efd0e2f9db487373266845bd4d9e53e6d6b7b4).

**Comment by colemanw** [comment]
I think that was a red herring. I've just discovered that running tests 
from within PHPStorm wipes my database, so that's what caused the 
problem on my end. Not sure about why it didn't work for Erich.
