### ISSUE TITLE
populate create method

### ISSUE THREAD

**Issue by ErichBSchulz** [civicrm/api4#5]
Civi\API\V4\Action::_run() is empty...

should it throw an exectption if this is by design?

or can it call something in the BAO??

**Comment by colemanw** [comment]
In order to get an MVP of this api out the door, I think yes for now it should do what `_civicrm_api3_basic_create()` does. Or maybe just call that function.

We could eventually look at replacing it under-the-hood with a more elegant system of events and listeners.

**Comment by ErichBSchulz** [comment]
we now have a working `participation` create via #25
