### ISSUE TITLE
populate delete action

### ISSUE THREAD

**Issue by ErichBSchulz** [civicrm/api4#6]
it is half done by looks of it

**Comment by ErichBSchulz** [comment]
I have delete working for participation - will do PR soon

**Comment by ErichBSchulz** [comment]
this is now actually merged but need to decide what the return values should be

I dont think I have it right

**Comment by ErichBSchulz** [comment]
@colemanw @eileenmcnaughton @xurizaemon et al - API4 can now delete and the only question is "should the return value be an array of IDs that have been deleted?"

if so we can close this :-)

**Comment by nganivet** [comment]
IMO we need to return at least the # of records deleted, and if no performance impact then the IDs as well.

**Comment by eileenmcnaughton** [comment]
Sounds like you are returning an array of ids already - as long as that is without performance cost that seems fine & you can close
