### ISSUE TITLE
Move the wiki page to the repo?

### ISSUE THREAD

**Issue by ErichBSchulz** [civicrm/api4#9]
we're moving the dev docs... would be good to move this too:

https://wiki.civicrm.org/confluence/display/CRM/API+v4+Spec

Most can be just dumped into the README

and the rest made into PRs and issues?

**Comment by colemanw** [comment]
:+1:

**Comment by ErichBSchulz** [comment]
just awaiting merge of the PR by@coleman and this one can be closed
